[package]
name = "libzerostash"
version = "0.1.0"
authors = ["Peter Parkanyi <me@rhapsodhy.hu>"]
repository = "https://github.com/rsdy/zerostash"
license = "GPL-3.0"
build = "build.rs"
edition= "2018"

[dependencies]
blake2b_simd = "0.5"
crossbeam-channel = "^0.3"
crossbeam-utils = "^0.6.6"
dashmap = "3.7"
getrandom = "0.1"
glob = { version = "0.3" }
itertools = "0.9"
libc = "0.2"
lru = "0.4"
lz4 = "^1.23.1"
memmap = "0.7"
ring = "0.16"
rust-argon2 = "0.8"
seahash = "3.0"
secrecy = "0.6"
serde = { version = "1.0", features = ["rc"] }
serde_cbor = "^0.10.1"
serde_derive = "1.0"
thiserror = "1.0"
walkdir = "^2.2.7"
zeroize = "1.1"

[dev-dependencies]